server:
  port: 8080

eureka:
  client:
    fetch-registry: true 
    registry-with-eureka: true 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: ms-student
          uri: lb://ms-student
          predicates:
            - Path=/student/**
        - id: ms-course
          uri: lb://ms-course
          predicates:
            - Path=/course/**
